import React, { useMemo, useState } from "react";
import quranEnglishRaw from "../../data/quran-en-saheeh.txt?raw";
import quranHindiRaw from "../../data/quran-hi-farooq-nadwi.txt?raw";
import quranUrduRaw from "../../data/quran-ur-jalandhry.txt?raw";

type Lang = "English" | "Hindi" | "Urdu";
type QuranResult = { ref: string; text: string };
type HadithResult = { collection: string; number?: string; grade?: string; arabic?: string; english?: string; reference?: string };
type Answer = { intro: string; explanation: string; quran: QuranResult[]; hadith: HadithResult[]; matchedTopic: string; note: string };
type TreeItem = { path: string; type: string };

const HADITH_TREE = "https://api.github.com/repos/CheeseWithSauce/HadithsJSONFormat/git/trees/main?recursive=1";
const HADITH_RAW = "https://raw.githubusercontent.com/CheeseWithSauce/HadithsJSONFormat/main/";
const CACHE_TREE = "mg-hadith-tree-v3";
const CACHE_PREFIX = "mg-hadith-file-v3:";

const normalize = (s: string) => s.toLowerCase().normalize("NFKC").replace(/[^a-z0-9\u0900-\u097f\u0600-\u06ff\s:.-]/gi, " ").replace(/\s+/g, " ").trim();
const parseQuran = (raw: string): QuranResult[] => raw.split(/\r?\n/).map(x => x.trim()).filter(Boolean).map((line, i) => { const m = line.match(/^(\d+)[|:\t](\d+)[|:\t](.*)$/); return m ? { ref: `Qur'an ${m[1]}:${m[2]}`, text: m[3].trim() } : { ref: `Qur'an passage ${i + 1}`, text: line }; });

const topics: Record<string, { words: string[]; hi: string[]; ur: string[] }> = {
  prayer: { words: ["prayer", "salah", "namaz", "pray", "salat", "five prayers"], hi: ["namaz", "नमाज़", "नमाज", "सलात", "प्रार्थना", "पाँच वक्त"], ur: ["نماز", "صلات", "پانچ وقت"] },
  patience: { words: ["patience", "patient", "sabr", "sabar", "hardship", "difficult", "difficulty", "trouble"], hi: ["sabr", "sabar", "सब्र", "मुश्किल", "परेशानी", "धैर्य", "मुसीबत"], ur: ["صبر", "مشکل", "پریشانی", "مصیبت"] },
  forgiveness: { words: ["forgive", "forgiveness", "repent", "mercy", "tawbah", "sin", "sins"], hi: ["माफ", "माफी", "तौबा", "गुनाह", "रहमत", "पाप"], ur: ["معافی", "معاف", "توبہ", "گناہ", "رحمت"] },
  charity: { words: ["charity", "charitable", "zakat", "sadaqah", "spend", "donation"], hi: ["ज़कात", "जकात", "सदका", "दान", "खैरात", "चैरिटी"], ur: ["زکوٰۃ", "زکات", "صدقہ", "خیرات", "چیریٹی"] },
  parents: { words: ["parents", "mother", "father", "parent", "walidain", "walid", "maa"], hi: ["माता", "पिता", "माँ", "बाप", "वालिदैन", "माता पिता", "मां बाप"], ur: ["والدین", "والد", "والدہ", "ماں", "باپ"] },
  marriage: { words: ["marriage", "marry", "husband", "wife", "spouse", "nikah"], hi: ["शादी", "विवाह", "निकाह", "पति", "पत्नी"], ur: ["شادی", "نکاح", "شوہر", "بیوی"] },
  anxiety: { words: ["anxiety", "worry", "fear", "sad", "stress", "heart", "depression"], hi: ["चिंता", "फिक्र", "डर", "उदासी", "तनाव", "दिल", "परेशान"], ur: ["فکر", "خوف", "اداسی", "تناؤ", "دل", "پریشان"] },
  fasting: { words: ["fast", "fasting", "ramadan", "ramadhan", "roza"], hi: ["रोज़ा", "रोजा", "उपवास", "रमज़ान", "रमजान"], ur: ["روزہ", "رمضان", "روزے"] },
  music: { words: ["music", "song", "songs", "instrument", "instruments"], hi: ["संगीत", "गाना", "गाने", "म्यूजिक"], ur: ["موسیقی", "گانا", "گانے"] },
  alcohol: { words: ["alcohol", "wine", "drinking", "intoxicant", "intoxicants", "khamr"], hi: ["शराब", "नशा", "मद्य"], ur: ["شراب", "نشہ", "خمر"] },
  food: { words: ["halal food", "haram food", "food", "meat", "pork", "halal", "haram"], hi: ["हलाल", "हराम", "खाना", "गोश्त", "सूअर"], ur: ["حلال", "حرام", "کھانا", "گوشت", "خنزیر"] },
  charityDebt: { words: ["debt", "loan", "owe", "borrow"], hi: ["कर्ज", "ऋण", "उधार", "क़र्ज़"], ur: ["قرض", "ادھار"] }
};

const topicAliases = (q: string) => { const n = normalize(q); const found: string[] = []; Object.entries(topics).forEach(([key, data]) => { if ([...data.words, ...data.hi, ...data.ur].some(w => n.includes(normalize(w)))) found.push(key); }); return found; };

const explanations: Record<string, { English: string; Hindi: string; Urdu: string }> = {
  prayer: { English: "Prayer (salah) is a central act of worship in Islam. The Qur'an repeatedly commands believers to establish prayer.", Hindi: "Namaz (सलात) Islam ki bahut important ibadat hai. Qur'an me baar-baar namaz qayam karne ka hukm diya gaya hai, isliye namaz ko regular farz ibadat ke taur par samjha jata hai.", Urdu: "نماز اسلام کی بنیادی عبادات میں سے ہے۔ قرآن میں بار بار نماز قائم کرنے کا حکم دیا گیا ہے، اس لیے اسے باقاعدہ فرض عبادت کے طور پر سمجھا جاتا ہے۔" },
  patience: { English: "Islam teaches patience (sabr), especially during hardship, while continuing to trust and obey Allah.", Hindi: "Islam mushkil waqt me sabr (सब्र) aur Allah par bharosa rakhne ki taleem deta hai. Sabr ka matlab haar maan lena nahi, balki pareshani me bhi sahi raaste par qayam rehna hai.", Urdu: "اسلام مشکل حالات میں صبر اور اللہ پر بھروسہ قائم رکھنے کی تعلیم دیتا ہے۔ صبر کا مطلب ہار مان لینا نہیں بلکہ آزمائش میں ثابت قدم رہنا ہے۔" },
  forgiveness: { English: "Islam strongly encourages sincere repentance and seeking Allah's forgiveness.", Hindi: "Islam sachchi tauba aur Allah se maafi maangne ki bahut honsla-afzai karta hai. Gunah chhodkar dil se tauba karni aur dobara usse bachne ki koshish karni chahiye.", Urdu: "اسلام سچی توبہ اور اللہ سے مغفرت طلب کرنے کی بھرپور ترغیب دیتا ہے۔" },
  parents: { English: "The Qur'an commands kindness, respect and good treatment toward parents.", Hindi: "Qur'an walidain (माता-पिता) ke saath achha sulook, izzat, shukr aur narmi se baat karne ki taleem deta hai. Allah ki nafarmani wale kaam me kisi ki ita'at zaroori nahi.", Urdu: "قرآن والدین کے ساتھ حسنِ سلوک، احترام اور نرمی سے بات کرنے کی تعلیم دیتا ہے۔" },
  fasting: { English: "Fasting in Ramadan is an important act of worship intended to develop taqwa and self-control.", Hindi: "Ramadan ka roza ek important ibadat hai. Iska maqsad taqwa (तक़वा), self-control aur Allah ki yaad ko badhana hai. Qur'an kuch situations me rukhsat ka bhi zikr karta hai.", Urdu: "رمضان کے روزے ایک اہم عبادت ہیں جن کا مقصد تقویٰ اور ضبطِ نفس کو بڑھانا ہے۔" },
  charity: { English: "Islam encourages charity and makes zakat a major obligation when its conditions are met.", Hindi: "Islam sadqa aur zakat ki honsla-afzai karta hai. Jin logon par zakat ki shartein poori hoti hain, unke liye zakat ek important farz hai. Dete waqt niyyat saaf honi chahiye.", Urdu: "اسلام صدقہ و خیرات کی ترغیب دیتا ہے اور شرائط پوری ہونے پر زکوٰۃ کو اہم فرض قرار دیتا ہے۔" },
  marriage: { English: "Marriage (nikah) is a lawful family relationship in Islam with rights and responsibilities for both spouses.", Hindi: "Nikah Islam me ek jaiz family relationship hai jisme husband aur wife dono ke rights aur responsibilities hoti hain. Specific fiqh matter ke liye qualified alim se mashwara behtar hai.", Urdu: "نکاح اسلام میں ایک جائز خاندانی رشتہ ہے جس میں دونوں میاں بیوی کے حقوق اور ذمہ داریاں ہیں۔" },
  anxiety: { English: "Islam encourages remembrance of Allah, prayer, patience and seeking help during distress.", Hindi: "Pareshaani, darr ya anxiety ke waqt Islam Allah ki yaad, namaz, sabr aur madad maangne ki taleem deta hai. Serious ya persistent problem me professional help lena bhi theek hai.", Urdu: "اسلام خوف اور پریشانی کے وقت اللہ کے ذکر، نماز اور صبر کی تعلیم دیتا ہے۔" },
  music: { English: "The ruling on music and instruments involves differing scholarly views and details about type and context.", Hindi: "Music aur instruments ke hukm me ulama ke darmiyan ikhtilaf milta hai. Isliye ek fiqhi rai ko sab ki muttahid rai ke taur par nahi batana chahiye; specific case ke liye qualified alim se poochna behtar hai.", Urdu: "موسیقی اور آلاتِ موسیقی کے حکم میں اہلِ علم کے درمیان اختلاف پایا جاتا ہے۔" },
  alcohol: { English: "The Qur'an clearly warns believers away from intoxicants.", Hindi: "Qur'an nasha aur intoxicants se door rehne ki clear hidayat deta hai aur unhe badi burai batata hai. Isliye sharab ki manahi Islamic fiqh me wazeh hai.", Urdu: "قرآن نشہ آور چیزوں سے بچنے کی واضح ہدایت دیتا ہے اور انہیں بڑی برائی قرار دیتا ہے۔" },
  food: { English: "Islam distinguishes between halal and haram food; the exact ruling depends on ingredients, preparation and evidence.", Hindi: "Islam halal aur haram khane me farq karta hai. Kisi specific food ka hukm uske ingredients, preparation aur daleel par depend karta hai; sirf naam dekhkar faisla nahi karna chahiye.", Urdu: "اسلام حلال اور حرام کھانے میں فرق کرتا ہے۔ کسی خاص کھانے کا حکم اس کے اجزاء اور تیاری پر منحصر ہو سکتا ہے۔" },
  charityDebt: { English: "Islam takes debts seriously and encourages fulfilling financial obligations.", Hindi: "Islam qarz aur financial zimmedariyon ko seriously leta hai aur qarz ada karne ki honsla-afzai karta hai. Specific case me contract aur circumstances dekhna zaroori hai.", Urdu: "اسلام قرض اور مالی ذمہ داریوں کو سنجیدگی سے لیتا ہے اور قرض ادا کرنے کی ترغیب دیتا ہے۔" }
};

function localQuran(q: string, lang: Lang): QuranResult[] { const nq = normalize(q); const keys = topicAliases(q); const expanded = keys.flatMap(k => topics[k].words); const words = [...nq.split(" ").filter(w => w.length > 2), ...expanded].map(normalize).filter(Boolean); const raw = lang === "Hindi" ? quranHindiRaw : lang === "Urdu" ? quranUrduRaw : quranEnglishRaw; const all = parseQuran(raw); return all.map(r => { const t = normalize(r.text); let score = 0; keys.forEach(k => topics[k].words.forEach(w => { if (t.includes(normalize(w))) score += 5; })); words.forEach(w => { if (t.includes(w)) score += 1; }); return { r, score }; }).filter(x => x.score > 0).sort((a,b) => b.score-a.score).slice(0,5).map(x => x.r); }

const pick = (obj: any, keys: string[]) => { for (const k of keys) if (obj && typeof obj[k] === "string" && obj[k].trim()) return obj[k].trim(); return undefined; };
function flattenHadith(node: any, path = "", out: HadithResult[] = []): HadithResult[] { if (!node) return out; if (Array.isArray(node)) { node.forEach((x, i) => flattenHadith(x, `${path}/${i}`, out)); return out; } if (typeof node !== "object") return out; const english = pick(node, ["english", "hadithEnglish", "English", "translation"]); const arabic = pick(node, ["arabic", "hadithArabic", "Arabic"]); const grade = pick(node, ["grade", "grading", "status", "authenticity"]); const number = pick(node, ["hadithNumber", "hadith_number", "number", "id"]); const reference = pick(node, ["reference", "ref", "bookReference"]); const collection = pick(node, ["collection", "book", "source"]) || path.split("/").filter(Boolean).find(x => /bukhari|muslim|abudawud|tirmidhi|nasai|ibn.?majah/i.test(x)) || "Hadith collection"; if ((english || arabic) && (grade || reference || number)) out.push({ collection, number, grade, arabic, english, reference }); Object.entries(node).forEach(([k,v]) => { if (v && typeof v === "object") flattenHadith(v, `${path}/${k}`, out); }); return out; }
const isGoodGrade = (g = "") => /sahih|hasan/i.test(g) && !/da.?if|weak|fabricated|mawdu/i.test(g);

async function loadHadithFiles(query: string): Promise<HadithResult[]> { try { let tree: TreeItem[] = []; const cached = localStorage.getItem(CACHE_TREE); if (cached) { try { tree = JSON.parse(cached); } catch {} } if (!tree.length) { const r = await fetch(HADITH_TREE); if (!r.ok) return []; const data = await r.json() as { tree?: TreeItem[] }; tree = (data.tree || []).filter(x => x.type === "blob" && x.path.startsWith("Sunnah/") && x.path.endsWith(".json")); localStorage.setItem(CACHE_TREE, JSON.stringify(tree)); } const targetFiles = tree.slice(0, 80); const all: HadithResult[] = []; for (const item of targetFiles) { const key = CACHE_PREFIX + item.path; let data: any = null; const cachedFile = localStorage.getItem(key); if (cachedFile) { try { data = JSON.parse(cachedFile); } catch {} } if (!data) { const r = await fetch(HADITH_RAW + item.path); if (!r.ok) continue; data = await r.json(); try { localStorage.setItem(key, JSON.stringify(data)); } catch {} } all.push(...flattenHadith(data, item.path)); } const nq = normalize(query); const keys = topicAliases(query); const searchTerms = [...nq.split(" ").filter(w => w.length > 2), ...keys.flatMap(k => topics[k].words)].map(normalize).filter(Boolean); return all.map(h => { const hay = normalize([h.english, h.arabic, h.reference, h.collection].filter(Boolean).join(" ")); let score = isGoodGrade(h.grade) ? 10 : 0; searchTerms.forEach(w => { if (hay.includes(w)) score += 2; }); return { h, score }; }).filter(x => x.score >= 12).sort((a,b) => b.score-a.score).slice(0,8).map(x => x.h).filter(h => isGoodGrade(h.grade)); } catch { return []; } }

async function answerFor(q: string, lang: Lang): Promise<Answer> { const keys = topicAliases(q); const quran = localQuran(q, lang); const hadith = await loadHadithFiles(q); const topic = keys[0] || "general question"; const explanation = explanations[topic]?.[lang] || (lang === "Hindi" ? "Is sawal ke liye relevant Qur'an aur Hadith references neeche diye gaye hain. Main answer ko easy Hinglish/Hindi me rakh raha hoon. Kisi specific fiqhi faisle ke liye qualified alim se mashwara karein." : lang === "Urdu" ? "اس سوال کے لیے متعلقہ قرآن اور حدیث کے حوالے نیچے دیے گئے ہیں۔ کسی خاص فقہی فیصلے کے لیے مستند عالم سے مشورہ کریں۔" : "I found relevant references in the local sources. Review the Qur'an and Hadith evidence below. For a specific fiqh ruling, consult a qualified scholar."); const intro = lang === "Hindi" ? "Aapke sawal ka short jawab easy Hinglish/Hindi me, phir Qur'an aur Hadith ke references diye gaye hain." : lang === "Urdu" ? "آپ کے سوال کا مختصر جواب اردو میں ہے، پھر متعلقہ قرآن اور حدیث کے حوالے نیچے دیے گئے ہیں۔" : "Here is a concise answer, followed by relevant Qur'an and Hadith references."; const note = lang === "Hindi" ? (hadith.length ? "Hadith me sirf Sahih/Hasan grading wali narrations ko prioritize kiya gaya hai. Sunan collections ki har narration automatically Sahih nahi hoti." : "Current indexed sources me matching Sahih/Hasan Hadith nahi mili.") : lang === "Urdu" ? (hadith.length ? "حدیث میں صحیح/حسن درجہ والی روایات کو ترجیح دی گئی ہے۔" : "موجودہ ذرائع میں متعلقہ صحیح/حسن حدیث نہیں ملی۔") : (hadith.length ? "Only Sahih/Hasan graded narrations are prioritized here. Not every narration in Sunan collections is automatically Sahih." : "No matching Sahih/Hasan Hadith was found in the currently indexed source files."); return { intro, explanation, quran, hadith, matchedTopic: topic, note }; }

export default function IslamicAI() {
  const [open, setOpen] = useState(false); const [q, setQ] = useState(""); const [loading, setLoading] = useState(false); const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mg-ai-lang") as Lang) || "English"); const [history, setHistory] = useState<{q:string; answer:Answer}[]>(() => { try { return JSON.parse(localStorage.getItem("mg-ai-history") || "[]"); } catch { return []; } }); const latest = history[0];
  const suggestions = useMemo(() => lang === "Hindi" ? ["Sabr ke baare me Qur'an aur Hadith kya kehte hain?", "Namaz kyu zaroori hai?", "Mata-pita ke haq kya hain?"] : lang === "Urdu" ? ["صبر کے بارے میں قرآن اور حدیث کیا کہتے ہیں؟", "نماز کیوں ضروری ہے؟", "والدین کے حقوق کیا ہیں؟"] : ["What do the Qur'an and Hadith say about patience?", "Why is prayer important?", "What do they say about parents?"], [lang]);
  const ask = async (text = q) => { const value = text.trim(); if (!value || loading) return; setLoading(true); try { const answer = await answerFor(value, lang); const next = [{ q:value, answer }, ...history].slice(0,10); setHistory(next); setQ(""); localStorage.setItem("mg-ai-history", JSON.stringify(next)); } finally { setLoading(false); } };
  const changeLang = (v:Lang) => { setLang(v); localStorage.setItem("mg-ai-lang", v); };
  if (!open) return <button onClick={() => setOpen(true)} aria-label="Open Islamic AI" style={{position:"fixed",left:18,bottom:22,zIndex:1000,border:0,borderRadius:999,padding:"12px 16px",display:"flex",gap:8,alignItems:"center",fontWeight:800,background:"#111827",color:"white",boxShadow:"0 10px 30px rgba(0,0,0,.25)",cursor:"pointer"}}>✨ Islamic AI</button>;
  const ui = lang === "Hindi" ? { title:"Islamic AI Assistant", sub:"Free • Qur'an + graded Hadith • Hinglish/Hindi answers", answer:"Hinglish / Hindi me jawab", quran:"📖 Qur'an ke references", hadith:"📚 Hadith ke references", noQ:"Clear local Qur'an match nahi mila.", noH:"Matching Sahih/Hasan Hadith nahi mili.", ask:"Pucho", placeholder:"Jaise: Namaz kyu zaroori hai?" } : lang === "Urdu" ? { title:"Islamic AI Assistant", sub:"Free • قرآن + مستند حدیث • اردو جوابات", answer:"اردو میں جواب", quran:"📖 قرآن کے حوالے", hadith:"📚 حدیث کے حوالے", noQ:"واضح قرآنی حوالہ نہیں ملا۔", noH:"متعلقہ صحیح/حسن حدیث نہیں ملی۔", ask:"پوچھیں", placeholder:"اپنا سوال اردو میں پوچھیں..." } : { title:"Islamic AI Assistant", sub:"Free • Qur'an + graded Hadith • Language-aware answers", answer:"Answer", quran:"📖 Qur'an references", hadith:"📚 Hadith references", noQ:"No clear local Qur'an match found.", noH:"No matching Sahih/Hasan Hadith found.", ask:"Ask", placeholder:"Ask about Qur'an or Hadith..." };
  return <div style={{position:"fixed",inset:0,zIndex:1100,background:"rgba(0,0,0,.45)",display:"flex",alignItems:"flex-end",justifyContent:"center"}}><section style={{width:"min(760px,100%)",maxHeight:"92vh",overflow:"auto",background:"white",borderRadius:"24px 24px 0 0",padding:20,boxSizing:"border-box",fontFamily:"system-ui"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1}}>MUSLIM GUIDE</div><h2 style={{margin:"4px 0"}}>{ui.title}</h2><small>{ui.sub}</small></div><button onClick={()=>setOpen(false)} style={{fontSize:24,border:0,background:"transparent",cursor:"pointer"}}>×</button></div>
    <div style={{display:"flex",gap:8,margin:"16px 0",flexWrap:"wrap"}}>{(["English","Hindi","Urdu"] as Lang[]).map(x=><button key={x} onClick={()=>changeLang(x)} style={{border:"1px solid #ddd",borderRadius:999,padding:"8px 12px",background:lang===x?"#111827":"white",color:lang===x?"white":"#111827"}}>{x}</button>)}</div>
    <div style={{display:"grid",gap:8}}>{suggestions.map(s=><button key={s} onClick={()=>void ask(s)} style={{textAlign:"left",padding:12,border:"1px solid #e5e7eb",borderRadius:14,background:"#f9fafb"}}>{s}</button>)}</div>
    <div style={{display:"flex",gap:8,marginTop:14}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder={ui.placeholder} style={{flex:1,padding:13,border:"1px solid #d1d5db",borderRadius:14}}/><button onClick={()=>void ask()} disabled={loading} style={{padding:"0 18px",border:0,borderRadius:14,background:"#111827",color:"white",fontWeight:800}}>{loading?"Searching…":ui.ask}</button></div>
    {latest&&<div style={{marginTop:18}}><div style={{fontWeight:800}}>Q: {latest.q}</div><p>{latest.answer.intro}</p><article style={{padding:16,margin:"10px 0",borderRadius:16,background:"#eef6ff",border:"1px solid #bfdbfe"}}><div style={{fontWeight:800,marginBottom:6}}>{ui.answer}</div><div style={{lineHeight:1.75}}>{latest.answer.explanation}</div></article>
      <h3 style={{marginBottom:8}}>{ui.quran}</h3>{latest.answer.quran.length ? latest.answer.quran.map(r=><article key={r.ref} style={{padding:14,margin:"10px 0",borderRadius:16,background:"#f5f7fa"}}><div style={{fontWeight:800,fontSize:13}}>{r.ref}</div><div style={{marginTop:6,lineHeight:1.6}}>{r.text}</div></article>) : <div style={{opacity:.7}}>{ui.noQ}</div>}
      <h3 style={{margin:"18px 0 8px"}}>{ui.hadith}</h3>{latest.answer.hadith.length ? latest.answer.hadith.map((h,i)=><article key={`${h.collection}-${h.number}-${i}`} style={{padding:14,margin:"10px 0",borderRadius:16,background:"#fff7ed",border:"1px solid #fed7aa"}}><div style={{fontWeight:800,fontSize:13}}>{h.collection}{h.number ? ` • Hadith ${h.number}` : ""}</div>{h.grade&&<div style={{display:"inline-block",marginTop:6,padding:"3px 8px",borderRadius:999,background:"#dcfce7",fontSize:12,fontWeight:800}}>{h.grade}</div>}{h.arabic&&<div dir="rtl" style={{marginTop:10,fontSize:18,lineHeight:1.9}}>{h.arabic}</div>}{h.english&&<div style={{marginTop:8,lineHeight:1.6}}>{h.english}</div>}{h.reference&&<div style={{marginTop:8,fontSize:12,opacity:.75}}>Reference: {h.reference}</div>}</article>) : <div style={{opacity:.7}}>{ui.noH}</div>}
      <div style={{fontSize:12,opacity:.7,marginTop:12}}>{latest.answer.note} {lang === "Hindi" ? "Reference-based assistant hai — fatwa service nahi." : lang === "Urdu" ? "یہ صرف حوالہ جاتی معاون ہے، فتویٰ سروس نہیں۔" : "Reference assistant only — not a fatwa service."}</div>
    </div>}
  </section></div>;
}
