import React, { useMemo, useState } from "react";
import quranEnglishRaw from "../../data/quran-en-saheeh.txt?raw";
import quranHindiRaw from "../../data/quran-hi-farooq-nadwi.txt?raw";
import quranUrduRaw from "../../data/quran-ur-jalandhry.txt?raw";

type Lang = "English" | "Hindi" | "Urdu";
type QuranResult = { ref: string; text: string };
type HadithResult = { collection: string; number?: string; grade?: string; arabic?: string; english?: string; reference?: string };
type Answer = { intro: string; explanation: string; quran: QuranResult[]; hadith: HadithResult[]; matchedTopic: string; note: string };
type TreeItem = { path: string; type: string };

const HADITH_TREE = "https://api.github.com/repos/CheeseWithSauce/HadithsJSONFormat/git/trees/main?recursive=1";
const HADITH_RAW = "https://raw.githubusercontent.com/CheeseWithSauce/HadithsJSONFormat/main/";
const CACHE_TREE = "mg-hadith-tree-v3";
const CACHE_PREFIX = "mg-hadith-file-v3:";

const normalize = (s: string) => s.toLowerCase().normalize("NFKC").replace(/[^a-z0-9\u0900-\u097f\u0600-\u06ff\s:.-]/gi, " ").replace(/\s+/g, " ").trim();
const parseQuran = (raw: string): QuranResult[] => raw.split(/\r?\n/).map(x => x.trim()).filter(Boolean).map((line, i) => { const m = line.match(/^(\d+)[|:\t](\d+)[|:\t](.*)$/); return m ? { ref: `Qur'an ${m[1]}:${m[2]}`, text: m[3].trim() } : { ref: `Qur'an passage ${i + 1}`, text: line }; });

const topics: Record<string, { words: string[]; hi: string[]; ur: string[] }> = {
  prayer: { words: ["prayer", "salah", "namaz", "pray", "salat", "five prayers"], hi: ["namaz", "नमाज़", "नमाज", "सलात", "प्रार्थना", "पाँच वक्त"], ur: ["نماز", "صلات", "پانچ وقت"] },
  patience: { words: ["patience", "patient", "sabr", "sabar", "hardship", "difficult", "difficulty", "trouble"], hi: ["sabr", "sabar", "सब्र", "मुश्किल", "परेशानी", "धैर्य", "मुसीबत"], ur: ["صبر", "مشکل", "پریشانی", "مصیبت"] },
  forgiveness: { words: ["forgive", "forgiveness", "repent", "mercy", "tawbah", "sin", "sins"], hi: ["माफ", "माफी", "तौबा", "गुनाह", "रहमत", "पाप"], ur: ["معافی", "معاف", "توبہ", "گناہ", "رحمت"] },
  charity: { words: ["charity", "charitable", "zakat", "sadaqah", "spend", "donation"], hi: ["ज़कात", "जकात", "सदका", "दान", "खैरात", "चैरिटी"], ur: ["زکوٰۃ", "زکات", "صدقہ", "خیرات", "چیریٹی"] },
  parents: { words: ["parents", "mother", "father", "parent", "walidain", "walid", "maa", "mother"], hi: ["माता", "पिता", "माँ", "बाप", "वालिदैन", "माता पिता", "मां बाप"], ur: ["والدین", "والد", "والدہ", "ماں", "باپ"] },
  marriage: { words: ["marriage", "marry", "husband", "wife", "spouse", "nikah"], hi: ["शादी", "विवाह", "निकाह", "पति", "पत्नी"], ur: ["شادی", "نکاح", "شوہر", "بیوی"] },
  anxiety: { words: ["anxiety", "worry", "fear", "sad", "stress", "heart", "depression"], hi: ["चिंता", "फिक्र", "डर", "उदासी", "तनाव", "दिल", "परेशान"], ur: ["فکر", "خوف", "اداسی", "تناؤ", "دل", "پریشان"] },
  fasting: { words: ["fast", "fasting", "ramadan", "ramadhan", "roza"], hi: ["रोज़ा", "रोजा", "उपवास", "रमज़ान", "रमजान"], ur: ["روزہ", "رمضان", "روزے"] },
  music: { words: ["music", "song", "songs", "instrument", "instruments"], hi: ["संगीत", "गाना", "गाने", "म्यूजिक"], ur: ["موسیقی", "گانا", "گانے"] },
  alcohol: { words: ["alcohol", "wine", "drinking", "intoxicant", "intoxicants", "khamr"], hi: ["शराब", "नशा", "मद्य"], ur: ["شراب", "نشہ", "خمر"] },
  food: { words: ["halal food", "haram food", "food", "meat", "pork", "halal", "haram"], hi: ["हलाल", "हराम", "खाना", "गोश्त", "सूअर"], ur: ["حلال", "حرام", "کھانا", "گوشت", "خنزیر"] },
  charityDebt: { words: ["debt", "loan", "owe", "borrow"], hi: ["कर्ज", "ऋण", "उधार", "क़र्ज़"], ur: ["قرض", "ادھار"] }
};

const topicAliases = (q: string) => { const n = normalize(q); const found: string[] = []; Object.entries(topics).forEach(([key, data]) => { if ([...data.words, ...data.hi, ...data.ur].some(w => n.includes(normalize(w)))) found.push(key); }); return found; };

const explanations: Record<string, { English: string; Hindi: string; Urdu: string }> = {
  prayer: { English: "Prayer (salah) is a central act of worship in Islam. The Qur'an repeatedly commands believers to establish prayer, so it should be treated as a regular obligation rather than only a voluntary practice.", Hindi: "नमाज़ (सलात) इस्लाम की बहुत महत्वपूर्ण इबादत है। क़ुरआन में बार-बार नमाज़ क़ायम करने का हुक्म दिया गया है, इसलिए इसे केवल वैकल्पिक इबादत नहीं बल्कि नियमित फ़र्ज़ इबादत के रूप में समझा जाता है।", Urdu: "نماز اسلام کی بنیادی عبادات میں سے ہے۔ قرآن میں بار بار نماز قائم کرنے کا حکم دیا گیا ہے، اس لیے اسے صرف اختیاری عبادت نہیں بلکہ باقاعدہ فرض عبادت کے طور پر سمجھا جاتا ہے۔" },
  patience: { English: "Islam teaches patience (sabr), especially during hardship, while continuing to trust and obey Allah. Patience does not mean giving up; it means remaining steadfast and avoiding wrongdoing during difficulty.", Hindi: "इस्लाम मुश्किल हालात में सब्र करने और अल्लाह पर भरोसा बनाए रखने की शिक्षा देता है। सब्र का मतलब हार मान लेना नहीं है, बल्कि परेशानी के दौरान सही रास्ते पर कायम रहना और गलत काम से बचना है।", Urdu: "اسلام مشکل حالات میں صبر اور اللہ پر بھروسہ قائم رکھنے کی تعلیم دیتا ہے۔ صبر کا مطلب ہار مان لینا نہیں بلکہ آزمائش میں ثابت قدم رہنا اور غلط کام سے بچنا ہے۔" },
  forgiveness: { English: "Islam strongly encourages repentance and seeking Allah's forgiveness. A person should sincerely turn away from sin, seek forgiveness, and try not to return to the wrongdoing.", Hindi: "इस्लाम सच्ची तौबा और अल्लाह से माफी मांगने की बहुत ज़ोरदार हौसला-अफ़ज़ाई करता है। इंसान को गुनाह छोड़कर सच्चे दिल से माफी मांगनी और दोबारा उस गुनाह से बचने की कोशिश करनी चाहिए।", Urdu: "اسلام سچی توبہ اور اللہ سے مغفرت طلب کرنے کی بھرپور ترغیب دیتا ہے۔ انسان کو گناہ چھوڑ کر اخلاص کے ساتھ معافی مانگنی اور دوبارہ اس گناہ سے بچنے کی کوشش کرنی چاہیے۔" },
  parents: { English: "The Qur'an commands kindness and good treatment toward parents. Respect, gratitude, gentle speech and care are emphasized, while obedience is not understood to require obeying a parent in disobedience to Allah.", Hindi: "क़ुरआन माता-पिता के साथ अच्छा व्यवहार, सम्मान, शुक्रगुज़ारी और नरमी से बात करने की शिक्षा देता है। हालांकि अल्लाह की नाफ़रमानी वाले काम में किसी की आज्ञा मानना आवश्यक नहीं माना जाता।", Urdu: "قرآن والدین کے ساتھ حسنِ سلوک، احترام، شکرگزاری اور نرمی سے بات کرنے کی تعلیم دیتا ہے۔ البتہ اللہ کی نافرمانی والے کام میں کسی کی اطاعت لازم نہیں سمجھی جاتی۔" },
  fasting: { English: "Fasting in Ramadan is an important act of worship intended to develop taqwa, self-control and awareness of Allah. The Qur'an gives the basic obligation and also mentions exemptions and concessions for certain circumstances.", Hindi: "रमज़ान का रोज़ा एक महत्वपूर्ण इबादत है जिसका उद्देश्य तक़वा, आत्म-संयम और अल्लाह की याद को बढ़ाना है। क़ुरआन रोज़े की मूल पाबंदी के साथ कुछ परिस्थितियों में रियायतों का भी उल्लेख करता है।", Urdu: "رمضان کے روزے ایک اہم عبادت ہیں جن کا مقصد تقویٰ، ضبطِ نفس اور اللہ کی یاد کو بڑھانا ہے۔ قرآن روزے کی بنیادی فرضیت کے ساتھ بعض حالات میں رخصتوں کا بھی ذکر کرتا ہے۔" },
  charity: { English: "Islam encourages charity and makes zakat a major obligation for those who meet its conditions. Giving should be sincere and should not be accompanied by humiliation or reminders of one's generosity.", Hindi: "इस्लाम सदक़ा और ज़कात की हौसला-अफ़ज़ाई करता है। जिन लोगों पर ज़कात की शर्तें पूरी होती हैं, उनके लिए ज़कात एक महत्वपूर्ण फ़र्ज़ है। दान देते समय नीयत साफ़ होनी चाहिए और एहसान जताने से बचना चाहिए।", Urdu: "اسلام صدقہ و خیرات کی ترغیب دیتا ہے اور شرائط پوری ہونے پر زکوٰۃ کو اہم فرض قرار دیتا ہے۔ صدقہ اخلاص کے ساتھ دینا چاہیے اور احسان جتانے یا کسی کی تحقیر سے بچنا چاہیے۔" },
  marriage: { English: "Marriage (nikah) is a lawful family relationship in Islam with rights and responsibilities for both spouses. Questions about specific conditions, divorce or disputed cases can depend on fiqh and should be checked with a qualified scholar.", Hindi: "निकाह इस्लाम में एक जायज़ पारिवारिक रिश्ता है जिसमें पति-पत्नी दोनों के अधिकार और जिम्मेदारियाँ होती हैं। निकाह की शर्तों, तलाक़ या किसी विशेष मामले के फ़िक़्ही हुक्म के लिए योग्य आलिम से सलाह लेना बेहतर है।", Urdu: "نکاح اسلام میں ایک جائز خاندانی رشتہ ہے جس میں دونوں میاں بیوی کے حقوق اور ذمہ داریاں ہیں۔ نکاح کی شرائط، طلاق یا کسی خاص فقہی مسئلے کے لیے مستند عالم سے مشورہ کرنا بہتر ہے۔" },
  anxiety: { English: "Islam encourages remembrance of Allah, prayer, patience and seeking help during fear or distress. For serious or persistent mental-health difficulties, religious support can be combined with appropriate professional care.", Hindi: "इस्लाम डर, चिंता और परेशानी के समय अल्लाह की याद, नमाज़, सब्र और मदद मांगने की शिक्षा देता है। लगातार या गंभीर मानसिक परेशानी में धार्मिक सहारे के साथ योग्य पेशेवर मदद लेना भी उचित है।", Urdu: "اسلام خوف، پریشانی اور اضطراب کے وقت اللہ کے ذکر، نماز، صبر اور مدد طلب کرنے کی تعلیم دیتا ہے۔ مسلسل یا شدید ذہنی پریشانی میں دینی رہنمائی کے ساتھ مناسب پیشہ ورانہ مدد لینا بھی درست ہے۔" },
  music: { English: "The ruling on music and instruments involves differing scholarly views and details about the type and context. The assistant should not present one disputed fiqh position as an uncontested fact; the cited texts should be reviewed with a qualified scholar.", Hindi: "संगीत और वाद्ययंत्रों के हुक्म में विद्वानों के बीच मतभेद और अलग-अलग विवरण मिलते हैं। इसलिए किसी एक फ़िक़्ही राय को निर्विवाद तथ्य की तरह पेश नहीं करना चाहिए; संबंधित दलीलों को योग्य आलिम के साथ देखना बेहतर है।", Urdu: "موسیقی اور آلاتِ موسیقی کے حکم میں اہلِ علم کے درمیان اختلاف اور تفصیلات پائی جاتی ہیں۔ اس لیے کسی ایک فقہی رائے کو قطعی متفق علیہ حقیقت کے طور پر پیش نہیں کرنا چاہیے؛ متعلقہ دلائل کو مستند عالم کے ساتھ دیکھنا بہتر ہے۔" },
  alcohol: { English: "The Qur'an explicitly warns believers away from intoxicants and describes them as a serious evil. Alcohol and other intoxicants therefore have a clear prohibition in mainstream Islamic jurisprudence.", Hindi: "क़ुरआन नशीली चीज़ों से दूर रहने की स्पष्ट हिदायत देता है और उन्हें गंभीर बुराई बताता है। इसलिए शराब और अन्य नशीले पदार्थों की मनाही इस्लामी फ़िक़्ह में स्पष्ट मानी जाती है।", Urdu: "قرآن نشہ آور چیزوں سے بچنے کی واضح ہدایت دیتا ہے اور انہیں بڑی برائی قرار دیتا ہے۔ اسی لیے شراب اور دیگر نشہ آور اشیاء کی ممانعت اسلامی فقہ میں واضح سمجھی جاتی ہے۔" },
  food: { English: "Islam distinguishes between lawful (halal) and unlawful (haram) food. The exact ruling depends on the food, ingredients, preparation and relevant evidence, so a specific product should be checked rather than judged from its name alone.", Hindi: "इस्लाम हलाल और हराम खाने में अंतर करता है। किसी खास खाने का हुक्म उसके ingredients, तैयारी और संबंधित दलील पर निर्भर कर सकता है, इसलिए केवल नाम देखकर फैसला नहीं करना चाहिए।", Urdu: "اسلام حلال اور حرام کھانے میں فرق کرتا ہے۔ کسی خاص کھانے کا حکم اس کے اجزاء، تیاری اور متعلقہ دلائل پر منحصر ہو سکتا ہے، اس لیے صرف نام کی بنیاد پر فیصلہ نہیں کرنا چاہیے۔" },
  charityDebt: { English: "Islam takes debts seriously and encourages fulfilling financial obligations. A person's exact duties can depend on the contract and circumstances, so specific debt disputes should be reviewed with a qualified scholar or appropriate legal adviser.", Hindi: "इस्लाम कर्ज़ और आर्थिक जिम्मेदारियों को गंभीरता से लेता है और कर्ज़ अदा करने की हौसला-अफ़ज़ाई करता है। किसी खास कर्ज़ के मामले में अनुबंध और परिस्थितियों के अनुसार हुक्म बदल सकता है, इसलिए विशेषज्ञ से सलाह लेना बेहतर है।", Urdu: "اسلام قرض اور مالی ذمہ داریوں کو سنجیدگی سے لیتا ہے اور قرض ادا کرنے کی ترغیب دیتا ہے۔ کسی خاص قرض کے معاملے میں معاہدے اور حالات کے لحاظ سے حکم مختلف ہو سکتا ہے، اس لیے ماہر سے مشورہ بہتر ہے۔" }
};

function localQuran(q: string, lang: Lang): QuranResult[] { const nq = normalize(q); const keys = topicAliases(q); const expanded = keys.flatMap(k => topics[k].words); const words = [...nq.split(" ").filter(w => w.length > 2), ...expanded].map(normalize).filter(Boolean); const raw = lang === "Hindi" ? quranHindiRaw : lang === "Urdu" ? quranUrduRaw : quranEnglishRaw; const all = parseQuran(raw); return all.map(r => { const t = normalize(r.text); let score = 0; keys.forEach(k => topics[k].words.forEach(w => { if (t.includes(normalize(w))) score += 5; })); words.forEach(w => { if (t.includes(w)) score += 1; }); return { r, score }; }).filter(x => x.score > 0).sort((a,b) => b.score-a.score).slice(0,5).map(x => x.r); }

const pick = (obj: any, keys: string[]) => { for (const k of keys) if (obj && typeof obj[k] === "string" && obj[k].trim()) return obj[k].trim(); return undefined; };
function flattenHadith(node: any, path = "", out: HadithResult[] = []): HadithResult[] { if (!node) return out; if (Array.isArray(node)) { node.forEach((x, i) => flattenHadith(x, `${path}/${i}`, out)); return out; } if (typeof node !== "object") return out; const english = pick(node, ["english", "hadithEnglish", "English", "translation"]); const arabic = pick(node, ["arabic", "hadithArabic", "Arabic"]); const grade = pick(node, ["grade", "grading", "status", "authenticity"]); const number = pick(node, ["hadithNumber", "hadith_number", "number", "id"]); const reference = pick(node, ["reference", "ref", "bookReference"]); const collection = pick(node, ["collection", "book", "source"]) || path.split("/").filter(Boolean).find(x => /bukhari|muslim|abudawud|tirmidhi|nasai|ibn.?majah/i.test(x)) || "Hadith collection"; if ((english || arabic) && (grade || reference || number)) out.push({ collection, number, grade, arabic, english, reference }); Object.entries(node).forEach(([k,v]) => { if (v && typeof v === "object") flattenHadith(v, `${path}/${k}`, out); }); return out; }
const isGoodGrade = (g = "") => /sahih|hasan/i.test(g) && !/da.?if|weak|fabricated|mawdu/i.test(g);

async function loadHadithFiles(query: string): Promise<HadithResult[]> { try { let tree: TreeItem[] = []; const cached = localStorage.getItem(CACHE_TREE); if (cached) { try { tree = JSON.parse(cached); } catch {} } if (!tree.length) { const r = await fetch(HADITH_TREE); if (!r.ok) return []; const data = await r.json() as { tree?: TreeItem[] }; tree = (data.tree || []).filter(x => x.type === "blob" && x.path.startsWith("Sunnah/") && x.path.endsWith(".json")); localStorage.setItem(CACHE_TREE, JSON.stringify(tree)); } const targetFiles = tree.slice(0, 80); const all: HadithResult[] = []; for (const item of targetFiles) { const key = CACHE_PREFIX + item.path; let data: any = null; const cachedFile = localStorage.getItem(key); if (cachedFile) { try { data = JSON.parse(cachedFile); } catch {} } if (!data) { const r = await fetch(HADITH_RAW + item.path); if (!r.ok) continue; data = await r.json(); try { localStorage.setItem(key, JSON.stringify(data)); } catch {} } all.push(...flattenHadith(data, item.path)); } const nq = normalize(query); const keys = topicAliases(query); const searchTerms = [...nq.split(" ").filter(w => w.length > 2), ...keys.flatMap(k => topics[k].words)].map(normalize).filter(Boolean); return all.map(h => { const hay = normalize([h.english, h.arabic, h.reference, h.collection].filter(Boolean).join(" ")); let score = isGoodGrade(h.grade) ? 10 : 0; searchTerms.forEach(w => { if (hay.includes(w)) score += 2; }); return { h, score }; }).filter(x => x.score >= 12).sort((a,b) => b.score-a.score).slice(0,8).map(x => x.h).filter(h => isGoodGrade(h.grade)); } catch { return []; } }

async function answerFor(q: string, lang: Lang): Promise<Answer> { const keys = topicAliases(q); const quran = localQuran(q, lang); const hadith = await loadHadithFiles(q); const topic = keys[0] || "general question"; const explanation = explanations[topic]?.[lang] || (lang === "Hindi" ? "इस सवाल के लिए मुझे स्थानीय स्रोतों में संबंधित संदर्भ मिले हैं। नीचे दिए गए क़ुरआन और हदीस के हवाले देखें। किसी विशेष फ़िक़्ही फैसले के लिए योग्य आलिम से सलाह लें।" : lang === "Urdu" ? "اس سوال کے لیے مقامی ذرائع میں متعلقہ حوالہ جات ملے ہیں۔ نیچے قرآن اور حدیث کے حوالے دیکھیں۔ کسی خاص فقہی فیصلے کے لیے مستند عالم سے مشورہ کریں۔" : "I found relevant references in the local sources. Review the Qur'an and Hadith evidence below. For a specific fiqh ruling, consult a qualified scholar."); const intro = lang === "Hindi" ? "आपके सवाल का संक्षिप्त जवाब हिंदी में, फिर संबंधित क़ुरआन और हदीस के references नीचे दिए गए हैं।" : lang === "Urdu" ? "آپ کے سوال کا مختصر جواب اردو میں ہے، پھر متعلقہ قرآن اور حدیث کے حوالے نیچے دیے گئے ہیں۔" : "Here is a concise answer, followed by relevant Qur'an and Hadith references."; const note = hadith.length ? "Hadith section mein sirf Sahih/Hasan grading wali narrations ko prioritize kiya gaya hai. Sunan collections ki har narration automatically Sahih nahi hoti." : "No matching Sahih/Hasan Hadith was found in the currently indexed source files."; return { intro, explanation, quran, hadith, matchedTopic: topic, note }; }

export default function IslamicAI() {
  const [open, setOpen] = useState(false); const [q, setQ] = useState(""); const [loading, setLoading] = useState(false); const [lang, setLang] = useState<Lang>(() => (localStorage.getItem("mg-ai-lang") as Lang) || "English"); const [history, setHistory] = useState<{q:string; answer:Answer}[]>(() => { try { return JSON.parse(localStorage.getItem("mg-ai-history") || "[]"); } catch { return []; } }); const latest = history[0];
  const suggestions = useMemo(() => lang === "Hindi" ? ["सब्र के बारे में क़ुरआन और हदीस क्या कहते हैं?", "नमाज़ क्यों ज़रूरी है?", "माता-पिता के हक़ क्या हैं?"] : lang === "Urdu" ? ["صبر کے بارے میں قرآن اور حدیث کیا کہتے ہیں؟", "نماز کیوں ضروری ہے؟", "والدین کے حقوق کیا ہیں؟"] : ["What do the Qur'an and Hadith say about patience?", "Why is prayer important?", "What do they say about parents?"], [lang]);
  const ask = async (text = q) => { const value = text.trim(); if (!value || loading) return; setLoading(true); try { const answer = await answerFor(value, lang); const next = [{ q:value, answer }, ...history].slice(0,10); setHistory(next); setQ(""); localStorage.setItem("mg-ai-history", JSON.stringify(next)); } finally { setLoading(false); } };
  const changeLang = (v:Lang) => { setLang(v); localStorage.setItem("mg-ai-lang", v); };
  if (!open) return <button onClick={() => setOpen(true)} aria-label="Open Islamic AI" style={{position:"fixed",left:18,bottom:22,zIndex:1000,border:0,borderRadius:999,padding:"12px 16px",display:"flex",gap:8,alignItems:"center",fontWeight:800,background:"#111827",color:"white",boxShadow:"0 10px 30px rgba(0,0,0,.25)",cursor:"pointer"}}>✨ Islamic AI</button>;
  return <div style={{position:"fixed",inset:0,zIndex:1100,background:"rgba(0,0,0,.45)",display:"flex",alignItems:"flex-end",justifyContent:"center"}}><section style={{width:"min(760px,100%)",maxHeight:"92vh",overflow:"auto",background:"white",borderRadius:"24px 24px 0 0",padding:20,boxSizing:"border-box",fontFamily:"system-ui"}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1}}>MUSLIM GUIDE</div><h2 style={{margin:"4px 0"}}>Islamic AI Assistant</h2><small>Free • Qur'an + graded Hadith • Language-aware answers</small></div><button onClick={()=>setOpen(false)} style={{fontSize:24,border:0,background:"transparent",cursor:"pointer"}}>×</button></div>
    <div style={{display:"flex",gap:8,margin:"16px 0",flexWrap:"wrap"}}>{(["English","Hindi","Urdu"] as Lang[]).map(x=><button key={x} onClick={()=>changeLang(x)} style={{border:"1px solid #ddd",borderRadius:999,padding:"8px 12px",background:lang===x?"#111827":"white",color:lang===x?"white":"#111827"}}>{x}</button>)}</div>
    <div style={{display:"grid",gap:8}}>{suggestions.map(s=><button key={s} onClick={()=>void ask(s)} style={{textAlign:"left",padding:12,border:"1px solid #e5e7eb",borderRadius:14,background:"#f9fafb"}}>{s}</button>)}</div>
    <div style={{display:"flex",gap:8,marginTop:14}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder={lang === "Hindi" ? "अपना सवाल हिंदी में पूछें..." : lang === "Urdu" ? "اپنا سوال اردو میں پوچھیں..." : "Ask about Qur'an or Hadith..."} style={{flex:1,padding:13,border:"1px solid #d1d5db",borderRadius:14}}/><button onClick={()=>void ask()} disabled={loading} style={{padding:"0 18px",border:0,borderRadius:14,background:"#111827",color:"white",fontWeight:800}}>{loading?"Searching…":"Ask"}</button></div>
    {latest&&<div style={{marginTop:18}}><div style={{fontWeight:800}}>Q: {latest.q}</div><p>{latest.answer.intro}</p><article style={{padding:16,margin:"10px 0",borderRadius:16,background:"#eef6ff",border:"1px solid #bfdbfe"}}><div style={{fontWeight:800,marginBottom:6}}>{lang === "Hindi" ? "हिंदी में जवाब" : lang === "Urdu" ? "اردو میں جواب" : "Answer"}</div><div style={{lineHeight:1.75}}>{latest.answer.explanation}</div></article>
      <h3 style={{marginBottom:8}}>📖 Qur'an references</h3>{latest.answer.quran.length ? latest.answer.quran.map(r=><article key={r.ref} style={{padding:14,margin:"10px 0",borderRadius:16,background:"#f5f7fa"}}><div style={{fontWeight:800,fontSize:13}}>{r.ref}</div><div style={{marginTop:6,lineHeight:1.6}}>{r.text}</div></article>) : <div style={{opacity:.7}}>No clear local Qur'an match found.</div>}
      <h3 style={{margin:"18px 0 8px"}}>📚 Hadith references</h3>{latest.answer.hadith.length ? latest.answer.hadith.map((h,i)=><article key={`${h.collection}-${h.number}-${i}`} style={{padding:14,margin:"10px 0",borderRadius:16,background:"#fff7ed",border:"1px solid #fed7aa"}}><div style={{fontWeight:800,fontSize:13}}>{h.collection}{h.number ? ` • Hadith ${h.number}` : ""}</div>{h.grade&&<div style={{display:"inline-block",marginTop:6,padding:"3px 8px",borderRadius:999,background:"#dcfce7",fontSize:12,fontWeight:800}}>{h.grade}</div>}{h.arabic&&<div dir="rtl" style={{marginTop:10,fontSize:18,lineHeight:1.9}}>{h.arabic}</div>}{h.english&&<div style={{marginTop:8,lineHeight:1.6}}>{h.english}</div>}{h.reference&&<div style={{marginTop:8,fontSize:12,opacity:.75}}>Reference: {h.reference}</div>}</article>) : <div style={{opacity:.7}}>No matching Sahih/Hasan Hadith found.</div>}
      <div style={{fontSize:12,opacity:.7,marginTop:12}}>{latest.answer.note} Reference assistant only — not a fatwa service.</div>
    </div>}
  </section></div>;
}
