import RamadanCalendarCard from "../ramadan/RamadanCalendarCard";
import React, { useEffect, useMemo, useState } from "react";
import MasjidJamaatCard from "../masjid/MasjidJamaatCard";
import { Coordinates, CalculationMethod, CalculationParameters, PrayerTimes, Madhab } from "adhan";
import { MapPin, Settings, Bell, BellOff, Sunrise, Sun, Sunset, Moon, Clock3, RefreshCw } from "lucide-react";
type CalculationMethodKey="karachi"|"mwl"|"egyptian"|"ummAlQura"|"northAmerica"|"moonsighting";
type PrayerRow={key:string;name:string;arabic:string;time:Date;icon:React.ReactNode};
const METHODS:Record<CalculationMethodKey,{label:string;create:()=>CalculationParameters}>={karachi:{label:"Karachi / South Asia",create:()=>CalculationMethod.Karachi()},mwl:{label:"Muslim World League",create:()=>CalculationMethod.MuslimWorldLeague()},egyptian:{label:"Egyptian General Authority",create:()=>CalculationMethod.Egyptian()},ummAlQura:{label:"Umm Al-Qura, Makkah",create:()=>CalculationMethod.UmmAlQura()},northAmerica:{label:"North America",create:()=>CalculationMethod.NorthAmerica()},moonsighting:{label:"Moonsighting Committee",create:()=>CalculationMethod.MoonsightingCommittee()}};
function formatTime(d:Date){return new Intl.DateTimeFormat("en-IN",{hour:"numeric",minute:"2-digit",hour12:true}).format(d)}
function formatDate(d:Date){return new Intl.DateTimeFormat("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d)}
function getHijriDate(d:Date){return new Intl.DateTimeFormat("en-TN-u-ca-islamic-umalqura",{day:"numeric",month:"long",year:"numeric"}).format(d)}
export default function PrayerPage(){
 const[latitude,setLatitude]=useState<number|null>(null),[longitude,setLongitude]=useState<number|null>(null),[locationName,setLocationName]=useState("Detecting location..."),[locationLoading,setLocationLoading]=useState(false);
 const[methodKey,setMethodKey]=useState<CalculationMethodKey>("karachi"),[madhab,setMadhab]=useState<"shafi"|"hanafi">("hanafi"),[adjustments,setAdjustments]=useState({fajr:0,dhuhr:0,asr:0,maghrib:0,isha:0}),[notifications,setNotifications]=useState(true),[showSettings,setShowSettings]=useState(false),[now,setNow]=useState(Date.now());
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{detectLocation()},[]);
 async function detectLocation(){if(!navigator.geolocation){setLocationName("Location unavailable");return}setLocationLoading(true);navigator.geolocation.getCurrentPosition(async p=>{const lat=p.coords.latitude,lon=p.coords.longitude;setLatitude(lat);setLongitude(lon);setLocationName("Current location");try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lon}`,{headers:{Accept:"application/json"}});if(r.ok){const a=(await r.json()).address||{};setLocationName(a.city||a.town||a.village||a.municipality||"Current location")}}catch{}finally{setLocationLoading(false)}},()=>{setLocationName("Location permission required");setLocationLoading(false)},{enableHighAccuracy:false,timeout:8000,maximumAge:900000})}
 const prayerTimes=useMemo(()=>{if(latitude===null||longitude===null)return null;const p=METHODS[methodKey].create();p.madhab=madhab==="hanafi"?Madhab.Hanafi:Madhab.Shafi;const t=new PrayerTimes(new Coordinates(latitude,longitude),new Date(),p);return{fajr:new Date(t.fajr.getTime()+adjustments.fajr*60000),sunrise:t.sunrise,dhuhr:new Date(t.dhuhr.getTime()+adjustments.dhuhr*60000),asr:new Date(t.asr.getTime()+adjustments.asr*60000),sunset:t.sunset,maghrib:new Date(t.maghrib.getTime()+adjustments.maghrib*60000),isha:new Date(t.isha.getTime()+adjustments.isha*60000)}},[latitude,longitude,methodKey,madhab,adjustments,Math.floor(now/60000)]);
 const prayers=useMemo<PrayerRow[]>(()=>prayerTimes?[{key:"fajr",name:"Fajr",arabic:"الفجر",time:prayerTimes.fajr,icon:<Moon size={20}/>},{key:"sunrise",name:"Sunrise",arabic:"الشروق",time:prayerTimes.sunrise,icon:<Sunrise size={20}/>},{key:"dhuhr",name:"Dhuhr",arabic:"الظهر",time:prayerTimes.dhuhr,icon:<Sun size={20}/>},{key:"asr",name:"Asr",arabic:"العصر",time:prayerTimes.asr,icon:<Sun size={20}/>},{key:"maghrib",name:"Maghrib",arabic:"المغرب",time:prayerTimes.maghrib,icon:<Sunset size={20}/>},{key:"isha",name:"Isha",arabic:"العشاء",time:prayerTimes.isha,icon:<Moon size={20}/>}]:[],[prayerTimes]);
 const nextPrayer=useMemo(()=>prayers.find(p=>p.time.getTime()>Date.now())||prayers[0]||null,[prayers,now]);
 const countdown=useMemo(()=>{if(!nextPrayer)return"";const s=Math.max(0,Math.floor((nextPrayer.time.getTime()-Date.now())/1000));return`${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor((s%3600)/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},[nextPrayer,now]);
 const updateAdjustment=(key:keyof typeof adjustments,value:number)=>setAdjustments(c=>({...c,[key]:value}));
 return <div className="page prayer-page"><div className="page-header"><div><div className="eyebrow">SALAH</div><h1>Prayer Times</h1><p>{formatDate(new Date())}</p><p>{getHijriDate(new Date())}</p></div><button className="icon-button" onClick={()=>setShowSettings(v=>!v)} aria-label="Prayer settings"><Settings size={20}/></button></div>
 <div className="prayer-location-card"><div className="prayer-location-main"><MapPin size={20}/><div><strong>{locationName}</strong>{latitude!==null&&longitude!==null&&<small>{latitude.toFixed(4)}, {longitude.toFixed(4)}</small>}</div></div><button className="secondary-button" onClick={detectLocation} disabled={locationLoading}><RefreshCw size={16}/>{locationLoading?"Detecting":"Refresh"}</button></div>
 {nextPrayer&&<section className="next-prayer-card"><div><span>Next Prayer</span><h2>{nextPrayer.name}</h2><div className="next-prayer-arabic">{nextPrayer.arabic}</div></div><div className="next-prayer-time"><strong>{formatTime(nextPrayer.time)}</strong><small>{countdown}</small></div></section>}
 <section className="prayer-list-card"><div className="section-heading"><div><span className="eyebrow">TODAY</span><h2>Namaz Times</h2></div><span className="method-badge">{METHODS[methodKey].label}</span></div><div className="prayer-rows">{prayers.map(p=><div key={p.key} className={`prayer-row ${nextPrayer?.key===p.key?"prayer-row-next":""}`}><div className="prayer-row-icon">{p.icon}</div><div className="prayer-row-name"><strong>{p.name}</strong><span>{p.arabic}</span></div><div className="prayer-row-time">{formatTime(p.time)}</div></div>)}</div></section>
 <section className="special-times-grid"><div className="special-time-card"><Clock3 size={18}/><span>Sehri End</span><strong>{prayerTimes?formatTime(new Date(prayerTimes.fajr.getTime()-600000)):"--:--"}</strong><small>10 min before Fajr</small></div><div className="special-time-card"><Sunset size={18}/><span>Iftar</span><strong>{prayerTimes?formatTime(prayerTimes.maghrib):"--:--"}</strong><small>At Maghrib</small></div></section><MasjidJamaatCard/><RamadanCalendarCard fajr={prayerTimes?.fajr??null} maghrib={prayerTimes?.maghrib??null}/>
 <section className="reminder-card"><div className="reminder-icon">{notifications?<Bell size={20}/>:<BellOff size={20}/>}</div><div className="reminder-content"><strong>Prayer Reminders</strong><span>{notifications?"Notifications are enabled":"Notifications are disabled"}</span></div><button className={`toggle-button ${notifications?"toggle-active":""}`} onClick={()=>setNotifications(v=>!v)}><span/></button></section>
 {showSettings&&<section className="prayer-settings-card"><div className="section-heading"><div><span className="eyebrow">CALCULATION</span><h2>Prayer Settings</h2></div></div><label className="settings-field"><span>Calculation Method</span><select value={methodKey} onChange={e=>setMethodKey(e.target.value as CalculationMethodKey)}>{Object.entries(METHODS).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><label className="settings-field"><span>Asr Juristic Method</span><select value={madhab} onChange={e=>setMadhab(e.target.value as "shafi"|"hanafi")}><option value="hanafi">Hanafi — 2× shadow</option><option value="shafi">Standard — 1× shadow</option></select></label><div className="adjustments-heading"><span>Minute Adjustments</span><small>Use only if your local timetable requires it.</small></div>{([['fajr','Fajr'],['dhuhr','Dhuhr'],['asr','Asr'],['maghrib','Maghrib'],['isha','Isha']] as const).map(([key,label])=><div className="adjustment-row" key={key}><span>{label}</span><div className="adjustment-controls"><button onClick={()=>updateAdjustment(key,adjustments[key]-1)}>-</button><strong>{adjustments[key]} min</strong><button onClick={()=>updateAdjustment(key,adjustments[key]+1)}>+</button></div></div>)}</section>}</div>
}
